node {
   def commit_id
   agent { label 'docker-slave-label' }
   stage('Preparation') {
     checkout scm
    //  save to temporary file
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     // nodejs installed plugin
     nodejs(nodeJSInstallationName: 'nodejs') {
       // dev, see package.json
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
       def app = docker.build("renegmedal/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
