version: "3.3"
services:
  web:
    container_name: web
    build: .
    depends_on:
      - db 
    command: node index-db.js
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: mysecurepass
      MYSQL_HOST: db
    

  db:
    container_name: db
    image: orchardup/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: mysecurepass
